// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Alliance is an object representing the database table.
type Alliance struct {
	ID          uint64    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name        string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Ticker      string    `boil:"ticker" json:"ticker" toml:"ticker" yaml:"ticker"`
	MemberCount uint64    `boil:"member_count" json:"member_count" toml:"member_count" yaml:"member_count"`
	IsClosed    int8      `boil:"is_closed" json:"is_closed" toml:"is_closed" yaml:"is_closed"`
	Etag        string    `boil:"etag" json:"etag" toml:"etag" yaml:"etag"`
	CachedUntil time.Time `boil:"cached_until" json:"cached_until" toml:"cached_until" yaml:"cached_until"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *allianceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L allianceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AllianceColumns = struct {
	ID          string
	Name        string
	Ticker      string
	MemberCount string
	IsClosed    string
	Etag        string
	CachedUntil string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "id",
	Name:        "name",
	Ticker:      "ticker",
	MemberCount: "member_count",
	IsClosed:    "is_closed",
	Etag:        "etag",
	CachedUntil: "cached_until",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

// Generated where

type whereHelperuint64 struct{ field string }

func (w whereHelperuint64) EQ(x uint64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperuint64) NEQ(x uint64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperuint64) LT(x uint64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperuint64) LTE(x uint64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperuint64) GT(x uint64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperuint64) GTE(x uint64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}

type whereHelperint8 struct{ field string }

func (w whereHelperint8) EQ(x int8) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint8) NEQ(x int8) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint8) LT(x int8) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint8) LTE(x int8) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint8) GT(x int8) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint8) GTE(x int8) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var AllianceWhere = struct {
	ID          whereHelperuint64
	Name        whereHelperstring
	Ticker      whereHelperstring
	MemberCount whereHelperuint64
	IsClosed    whereHelperint8
	Etag        whereHelperstring
	CachedUntil whereHelpertime_Time
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
}{
	ID:          whereHelperuint64{field: "`alliances`.`id`"},
	Name:        whereHelperstring{field: "`alliances`.`name`"},
	Ticker:      whereHelperstring{field: "`alliances`.`ticker`"},
	MemberCount: whereHelperuint64{field: "`alliances`.`member_count`"},
	IsClosed:    whereHelperint8{field: "`alliances`.`is_closed`"},
	Etag:        whereHelperstring{field: "`alliances`.`etag`"},
	CachedUntil: whereHelpertime_Time{field: "`alliances`.`cached_until`"},
	CreatedAt:   whereHelpertime_Time{field: "`alliances`.`created_at`"},
	UpdatedAt:   whereHelpertime_Time{field: "`alliances`.`updated_at`"},
}

// AllianceRels is where relationship names are stored.
var AllianceRels = struct {
	KillmailAttackers string
	KillmailVictims   string
}{
	KillmailAttackers: "KillmailAttackers",
	KillmailVictims:   "KillmailVictims",
}

// allianceR is where relationships are stored.
type allianceR struct {
	KillmailAttackers KillmailAttackerSlice
	KillmailVictims   KillmailVictimSlice
}

// NewStruct creates a new relationship struct
func (*allianceR) NewStruct() *allianceR {
	return &allianceR{}
}

// allianceL is where Load methods for each relationship are stored.
type allianceL struct{}

var (
	allianceAllColumns            = []string{"id", "name", "ticker", "member_count", "is_closed", "etag", "cached_until", "created_at", "updated_at"}
	allianceColumnsWithoutDefault = []string{"id", "name", "ticker", "etag", "cached_until", "created_at", "updated_at"}
	allianceColumnsWithDefault    = []string{"member_count", "is_closed"}
	alliancePrimaryKeyColumns     = []string{"id"}
)

type (
	// AllianceSlice is an alias for a slice of pointers to Alliance.
	// This should generally be used opposed to []Alliance.
	AllianceSlice []*Alliance

	allianceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	allianceType                 = reflect.TypeOf(&Alliance{})
	allianceMapping              = queries.MakeStructMapping(allianceType)
	alliancePrimaryKeyMapping, _ = queries.BindMapping(allianceType, allianceMapping, alliancePrimaryKeyColumns)
	allianceInsertCacheMut       sync.RWMutex
	allianceInsertCache          = make(map[string]insertCache)
	allianceUpdateCacheMut       sync.RWMutex
	allianceUpdateCache          = make(map[string]updateCache)
	allianceUpsertCacheMut       sync.RWMutex
	allianceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single alliance record from the query.
func (q allianceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Alliance, error) {
	o := &Alliance{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: failed to execute a one query for alliances")
	}

	return o, nil
}

// All returns all Alliance records from the query.
func (q allianceQuery) All(ctx context.Context, exec boil.ContextExecutor) (AllianceSlice, error) {
	var o []*Alliance

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "boiler: failed to assign all query results to Alliance slice")
	}

	return o, nil
}

// Count returns the count of all Alliance records in the query.
func (q allianceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to count alliances rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q allianceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "boiler: failed to check if alliances exists")
	}

	return count > 0, nil
}

// KillmailAttackers retrieves all the killmail_attacker's KillmailAttackers with an executor.
func (o *Alliance) KillmailAttackers(mods ...qm.QueryMod) killmailAttackerQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`killmail_attackers`.`alliance_id`=?", o.ID),
	)

	query := KillmailAttackers(queryMods...)
	queries.SetFrom(query.Query, "`killmail_attackers`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`killmail_attackers`.*"})
	}

	return query
}

// KillmailVictims retrieves all the killmail_victim's KillmailVictims with an executor.
func (o *Alliance) KillmailVictims(mods ...qm.QueryMod) killmailVictimQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`killmail_victim`.`alliance_id`=?", o.ID),
	)

	query := KillmailVictims(queryMods...)
	queries.SetFrom(query.Query, "`killmail_victim`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`killmail_victim`.*"})
	}

	return query
}

// LoadKillmailAttackers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (allianceL) LoadKillmailAttackers(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAlliance interface{}, mods queries.Applicator) error {
	var slice []*Alliance
	var object *Alliance

	if singular {
		object = maybeAlliance.(*Alliance)
	} else {
		slice = *maybeAlliance.(*[]*Alliance)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &allianceR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &allianceR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`killmail_attackers`), qm.WhereIn(`killmail_attackers.alliance_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load killmail_attackers")
	}

	var resultSlice []*KillmailAttacker
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice killmail_attackers")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on killmail_attackers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for killmail_attackers")
	}

	if singular {
		object.R.KillmailAttackers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &killmailAttackerR{}
			}
			foreign.R.Alliance = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.AllianceID) {
				local.R.KillmailAttackers = append(local.R.KillmailAttackers, foreign)
				if foreign.R == nil {
					foreign.R = &killmailAttackerR{}
				}
				foreign.R.Alliance = local
				break
			}
		}
	}

	return nil
}

// LoadKillmailVictims allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (allianceL) LoadKillmailVictims(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAlliance interface{}, mods queries.Applicator) error {
	var slice []*Alliance
	var object *Alliance

	if singular {
		object = maybeAlliance.(*Alliance)
	} else {
		slice = *maybeAlliance.(*[]*Alliance)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &allianceR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &allianceR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`killmail_victim`), qm.WhereIn(`killmail_victim.alliance_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load killmail_victim")
	}

	var resultSlice []*KillmailVictim
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice killmail_victim")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on killmail_victim")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for killmail_victim")
	}

	if singular {
		object.R.KillmailVictims = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &killmailVictimR{}
			}
			foreign.R.Alliance = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.AllianceID) {
				local.R.KillmailVictims = append(local.R.KillmailVictims, foreign)
				if foreign.R == nil {
					foreign.R = &killmailVictimR{}
				}
				foreign.R.Alliance = local
				break
			}
		}
	}

	return nil
}

// AddKillmailAttackers adds the given related objects to the existing relationships
// of the alliance, optionally inserting them as new records.
// Appends related to o.R.KillmailAttackers.
// Sets related.R.Alliance appropriately.
func (o *Alliance) AddKillmailAttackers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*KillmailAttacker) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.AllianceID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `killmail_attackers` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"alliance_id"}),
				strmangle.WhereClause("`", "`", 0, killmailAttackerPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.AllianceID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &allianceR{
			KillmailAttackers: related,
		}
	} else {
		o.R.KillmailAttackers = append(o.R.KillmailAttackers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &killmailAttackerR{
				Alliance: o,
			}
		} else {
			rel.R.Alliance = o
		}
	}
	return nil
}

// SetKillmailAttackers removes all previously related items of the
// alliance replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Alliance's KillmailAttackers accordingly.
// Replaces o.R.KillmailAttackers with related.
// Sets related.R.Alliance's KillmailAttackers accordingly.
func (o *Alliance) SetKillmailAttackers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*KillmailAttacker) error {
	query := "update `killmail_attackers` set `alliance_id` = null where `alliance_id` = ?"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.KillmailAttackers {
			queries.SetScanner(&rel.AllianceID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Alliance = nil
		}

		o.R.KillmailAttackers = nil
	}
	return o.AddKillmailAttackers(ctx, exec, insert, related...)
}

// RemoveKillmailAttackers relationships from objects passed in.
// Removes related items from R.KillmailAttackers (uses pointer comparison, removal does not keep order)
// Sets related.R.Alliance.
func (o *Alliance) RemoveKillmailAttackers(ctx context.Context, exec boil.ContextExecutor, related ...*KillmailAttacker) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.AllianceID, nil)
		if rel.R != nil {
			rel.R.Alliance = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("alliance_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.KillmailAttackers {
			if rel != ri {
				continue
			}

			ln := len(o.R.KillmailAttackers)
			if ln > 1 && i < ln-1 {
				o.R.KillmailAttackers[i] = o.R.KillmailAttackers[ln-1]
			}
			o.R.KillmailAttackers = o.R.KillmailAttackers[:ln-1]
			break
		}
	}

	return nil
}

// AddKillmailVictims adds the given related objects to the existing relationships
// of the alliance, optionally inserting them as new records.
// Appends related to o.R.KillmailVictims.
// Sets related.R.Alliance appropriately.
func (o *Alliance) AddKillmailVictims(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*KillmailVictim) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.AllianceID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `killmail_victim` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"alliance_id"}),
				strmangle.WhereClause("`", "`", 0, killmailVictimPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.AllianceID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &allianceR{
			KillmailVictims: related,
		}
	} else {
		o.R.KillmailVictims = append(o.R.KillmailVictims, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &killmailVictimR{
				Alliance: o,
			}
		} else {
			rel.R.Alliance = o
		}
	}
	return nil
}

// SetKillmailVictims removes all previously related items of the
// alliance replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Alliance's KillmailVictims accordingly.
// Replaces o.R.KillmailVictims with related.
// Sets related.R.Alliance's KillmailVictims accordingly.
func (o *Alliance) SetKillmailVictims(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*KillmailVictim) error {
	query := "update `killmail_victim` set `alliance_id` = null where `alliance_id` = ?"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.KillmailVictims {
			queries.SetScanner(&rel.AllianceID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Alliance = nil
		}

		o.R.KillmailVictims = nil
	}
	return o.AddKillmailVictims(ctx, exec, insert, related...)
}

// RemoveKillmailVictims relationships from objects passed in.
// Removes related items from R.KillmailVictims (uses pointer comparison, removal does not keep order)
// Sets related.R.Alliance.
func (o *Alliance) RemoveKillmailVictims(ctx context.Context, exec boil.ContextExecutor, related ...*KillmailVictim) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.AllianceID, nil)
		if rel.R != nil {
			rel.R.Alliance = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("alliance_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.KillmailVictims {
			if rel != ri {
				continue
			}

			ln := len(o.R.KillmailVictims)
			if ln > 1 && i < ln-1 {
				o.R.KillmailVictims[i] = o.R.KillmailVictims[ln-1]
			}
			o.R.KillmailVictims = o.R.KillmailVictims[:ln-1]
			break
		}
	}

	return nil
}

// Alliances retrieves all the records using an executor.
func Alliances(mods ...qm.QueryMod) allianceQuery {
	mods = append(mods, qm.From("`alliances`"))
	return allianceQuery{NewQuery(mods...)}
}

// FindAlliance retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAlliance(ctx context.Context, exec boil.ContextExecutor, iD uint64, selectCols ...string) (*Alliance, error) {
	allianceObj := &Alliance{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `alliances` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, allianceObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: unable to select from alliances")
	}

	return allianceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Alliance) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no alliances provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(allianceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	allianceInsertCacheMut.RLock()
	cache, cached := allianceInsertCache[key]
	allianceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			allianceAllColumns,
			allianceColumnsWithDefault,
			allianceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(allianceType, allianceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(allianceType, allianceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `alliances` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `alliances` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `alliances` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, alliancePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "boiler: unable to insert into alliances")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to populate default values for alliances")
	}

CacheNoHooks:
	if !cached {
		allianceInsertCacheMut.Lock()
		allianceInsertCache[key] = cache
		allianceInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Alliance.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Alliance) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	allianceUpdateCacheMut.RLock()
	cache, cached := allianceUpdateCache[key]
	allianceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			allianceAllColumns,
			alliancePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("boiler: unable to update alliances, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `alliances` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, alliancePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(allianceType, allianceMapping, append(wl, alliancePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update alliances row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by update for alliances")
	}

	if !cached {
		allianceUpdateCacheMut.Lock()
		allianceUpdateCache[key] = cache
		allianceUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q allianceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all for alliances")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected for alliances")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AllianceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("boiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), alliancePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `alliances` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, alliancePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all in alliance slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected all in update all alliance")
	}
	return rowsAff, nil
}

var mySQLAllianceUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Alliance) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no alliances provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(allianceColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLAllianceUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	allianceUpsertCacheMut.RLock()
	cache, cached := allianceUpsertCache[key]
	allianceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			allianceAllColumns,
			allianceColumnsWithDefault,
			allianceColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			allianceAllColumns,
			alliancePrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("boiler: unable to upsert alliances, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "alliances", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `alliances` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(allianceType, allianceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(allianceType, allianceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "boiler: unable to upsert for alliances")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(allianceType, allianceMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to retrieve unique values for alliances")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to populate default values for alliances")
	}

CacheNoHooks:
	if !cached {
		allianceUpsertCacheMut.Lock()
		allianceUpsertCache[key] = cache
		allianceUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Alliance record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Alliance) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("boiler: no Alliance provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), alliancePrimaryKeyMapping)
	sql := "DELETE FROM `alliances` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete from alliances")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by delete for alliances")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q allianceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("boiler: no allianceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from alliances")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for alliances")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AllianceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), alliancePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `alliances` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, alliancePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from alliance slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for alliances")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Alliance) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAlliance(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AllianceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AllianceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), alliancePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `alliances`.* FROM `alliances` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, alliancePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to reload all in AllianceSlice")
	}

	*o = slice

	return nil
}

// AllianceExists checks if the Alliance row exists.
func AllianceExists(ctx context.Context, exec boil.ContextExecutor, iD uint64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `alliances` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "boiler: unable to check if alliances exists")
	}

	return exists, nil
}
