// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var TableNames = struct {
	Alliances          string
	BlueprintMaterials string
	BlueprintProducts  string
	Characters         string
	Constellations     string
	Corporations       string
	Factions           string
	KillmailAttackers  string
	KillmailItems      string
	KillmailVictim     string
	Killmails          string
	Prices             string
	PricesBuilt        string
	Regions            string
	SolarSystems       string
	Tokens             string
	TypeAttributes     string
	TypeCategories     string
	TypeFlags          string
	TypeGroups         string
	Types              string
}{
	Alliances:          "alliances",
	BlueprintMaterials: "blueprint_materials",
	BlueprintProducts:  "blueprint_products",
	Characters:         "characters",
	Constellations:     "constellations",
	Corporations:       "corporations",
	Factions:           "factions",
	KillmailAttackers:  "killmail_attackers",
	KillmailItems:      "killmail_items",
	KillmailVictim:     "killmail_victim",
	Killmails:          "killmails",
	Prices:             "prices",
	PricesBuilt:        "prices_built",
	Regions:            "regions",
	SolarSystems:       "solar_systems",
	Tokens:             "tokens",
	TypeAttributes:     "type_attributes",
	TypeCategories:     "type_categories",
	TypeFlags:          "type_flags",
	TypeGroups:         "type_groups",
	Types:              "types",
}
