// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
	"github.com/volatiletech/sqlboiler/types"
)

// KillmailVictim is an object representing the database table.
type KillmailVictim struct {
	ID            uint64        `boil:"id" json:"id" toml:"id" yaml:"id"`
	KillmailID    uint64        `boil:"killmail_id" json:"killmail_id" toml:"killmail_id" yaml:"killmail_id"`
	AllianceID    null.Uint64   `boil:"alliance_id" json:"alliance_id,omitempty" toml:"alliance_id" yaml:"alliance_id,omitempty"`
	CharacterID   null.Uint64   `boil:"character_id" json:"character_id,omitempty" toml:"character_id" yaml:"character_id,omitempty"`
	CorporationID uint64        `boil:"corporation_id" json:"corporation_id" toml:"corporation_id" yaml:"corporation_id"`
	FactionID     null.Uint64   `boil:"faction_id" json:"faction_id,omitempty" toml:"faction_id" yaml:"faction_id,omitempty"`
	DamageTaken   uint64        `boil:"damage_taken" json:"damage_taken" toml:"damage_taken" yaml:"damage_taken"`
	ShipTypeID    uint64        `boil:"ship_type_id" json:"ship_type_id" toml:"ship_type_id" yaml:"ship_type_id"`
	PosX          types.Decimal `boil:"pos_x" json:"pos_x" toml:"pos_x" yaml:"pos_x"`
	PosY          types.Decimal `boil:"pos_y" json:"pos_y" toml:"pos_y" yaml:"pos_y"`
	PosZ          types.Decimal `boil:"pos_z" json:"pos_z" toml:"pos_z" yaml:"pos_z"`
	CreatedAt     time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time     `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *killmailVictimR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L killmailVictimL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var KillmailVictimColumns = struct {
	ID            string
	KillmailID    string
	AllianceID    string
	CharacterID   string
	CorporationID string
	FactionID     string
	DamageTaken   string
	ShipTypeID    string
	PosX          string
	PosY          string
	PosZ          string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "id",
	KillmailID:    "killmail_id",
	AllianceID:    "alliance_id",
	CharacterID:   "character_id",
	CorporationID: "corporation_id",
	FactionID:     "faction_id",
	DamageTaken:   "damage_taken",
	ShipTypeID:    "ship_type_id",
	PosX:          "pos_x",
	PosY:          "pos_y",
	PosZ:          "pos_z",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

// Generated where

var KillmailVictimWhere = struct {
	ID            whereHelperuint64
	KillmailID    whereHelperuint64
	AllianceID    whereHelpernull_Uint64
	CharacterID   whereHelpernull_Uint64
	CorporationID whereHelperuint64
	FactionID     whereHelpernull_Uint64
	DamageTaken   whereHelperuint64
	ShipTypeID    whereHelperuint64
	PosX          whereHelpertypes_Decimal
	PosY          whereHelpertypes_Decimal
	PosZ          whereHelpertypes_Decimal
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
}{
	ID:            whereHelperuint64{field: "`killmail_victim`.`id`"},
	KillmailID:    whereHelperuint64{field: "`killmail_victim`.`killmail_id`"},
	AllianceID:    whereHelpernull_Uint64{field: "`killmail_victim`.`alliance_id`"},
	CharacterID:   whereHelpernull_Uint64{field: "`killmail_victim`.`character_id`"},
	CorporationID: whereHelperuint64{field: "`killmail_victim`.`corporation_id`"},
	FactionID:     whereHelpernull_Uint64{field: "`killmail_victim`.`faction_id`"},
	DamageTaken:   whereHelperuint64{field: "`killmail_victim`.`damage_taken`"},
	ShipTypeID:    whereHelperuint64{field: "`killmail_victim`.`ship_type_id`"},
	PosX:          whereHelpertypes_Decimal{field: "`killmail_victim`.`pos_x`"},
	PosY:          whereHelpertypes_Decimal{field: "`killmail_victim`.`pos_y`"},
	PosZ:          whereHelpertypes_Decimal{field: "`killmail_victim`.`pos_z`"},
	CreatedAt:     whereHelpertime_Time{field: "`killmail_victim`.`created_at`"},
	UpdatedAt:     whereHelpertime_Time{field: "`killmail_victim`.`updated_at`"},
}

// KillmailVictimRels is where relationship names are stored.
var KillmailVictimRels = struct {
	Alliance    string
	Character   string
	Corporation string
	Faction     string
	Killmail    string
	ShipType    string
}{
	Alliance:    "Alliance",
	Character:   "Character",
	Corporation: "Corporation",
	Faction:     "Faction",
	Killmail:    "Killmail",
	ShipType:    "ShipType",
}

// killmailVictimR is where relationships are stored.
type killmailVictimR struct {
	Alliance    *Alliance
	Character   *Character
	Corporation *Corporation
	Faction     *Faction
	Killmail    *Killmail
	ShipType    *Type
}

// NewStruct creates a new relationship struct
func (*killmailVictimR) NewStruct() *killmailVictimR {
	return &killmailVictimR{}
}

// killmailVictimL is where Load methods for each relationship are stored.
type killmailVictimL struct{}

var (
	killmailVictimAllColumns            = []string{"id", "killmail_id", "alliance_id", "character_id", "corporation_id", "faction_id", "damage_taken", "ship_type_id", "pos_x", "pos_y", "pos_z", "created_at", "updated_at"}
	killmailVictimColumnsWithoutDefault = []string{"killmail_id", "alliance_id", "character_id", "corporation_id", "faction_id", "damage_taken", "ship_type_id", "pos_x", "pos_y", "pos_z", "created_at", "updated_at"}
	killmailVictimColumnsWithDefault    = []string{"id"}
	killmailVictimPrimaryKeyColumns     = []string{"id"}
)

type (
	// KillmailVictimSlice is an alias for a slice of pointers to KillmailVictim.
	// This should generally be used opposed to []KillmailVictim.
	KillmailVictimSlice []*KillmailVictim

	killmailVictimQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	killmailVictimType                 = reflect.TypeOf(&KillmailVictim{})
	killmailVictimMapping              = queries.MakeStructMapping(killmailVictimType)
	killmailVictimPrimaryKeyMapping, _ = queries.BindMapping(killmailVictimType, killmailVictimMapping, killmailVictimPrimaryKeyColumns)
	killmailVictimInsertCacheMut       sync.RWMutex
	killmailVictimInsertCache          = make(map[string]insertCache)
	killmailVictimUpdateCacheMut       sync.RWMutex
	killmailVictimUpdateCache          = make(map[string]updateCache)
	killmailVictimUpsertCacheMut       sync.RWMutex
	killmailVictimUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single killmailVictim record from the query.
func (q killmailVictimQuery) One(ctx context.Context, exec boil.ContextExecutor) (*KillmailVictim, error) {
	o := &KillmailVictim{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: failed to execute a one query for killmail_victim")
	}

	return o, nil
}

// All returns all KillmailVictim records from the query.
func (q killmailVictimQuery) All(ctx context.Context, exec boil.ContextExecutor) (KillmailVictimSlice, error) {
	var o []*KillmailVictim

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "boiler: failed to assign all query results to KillmailVictim slice")
	}

	return o, nil
}

// Count returns the count of all KillmailVictim records in the query.
func (q killmailVictimQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to count killmail_victim rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q killmailVictimQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "boiler: failed to check if killmail_victim exists")
	}

	return count > 0, nil
}

// Alliance pointed to by the foreign key.
func (o *KillmailVictim) Alliance(mods ...qm.QueryMod) allianceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.AllianceID),
	}

	queryMods = append(queryMods, mods...)

	query := Alliances(queryMods...)
	queries.SetFrom(query.Query, "`alliances`")

	return query
}

// Character pointed to by the foreign key.
func (o *KillmailVictim) Character(mods ...qm.QueryMod) characterQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.CharacterID),
	}

	queryMods = append(queryMods, mods...)

	query := Characters(queryMods...)
	queries.SetFrom(query.Query, "`characters`")

	return query
}

// Corporation pointed to by the foreign key.
func (o *KillmailVictim) Corporation(mods ...qm.QueryMod) corporationQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.CorporationID),
	}

	queryMods = append(queryMods, mods...)

	query := Corporations(queryMods...)
	queries.SetFrom(query.Query, "`corporations`")

	return query
}

// Faction pointed to by the foreign key.
func (o *KillmailVictim) Faction(mods ...qm.QueryMod) factionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.FactionID),
	}

	queryMods = append(queryMods, mods...)

	query := Factions(queryMods...)
	queries.SetFrom(query.Query, "`factions`")

	return query
}

// Killmail pointed to by the foreign key.
func (o *KillmailVictim) Killmail(mods ...qm.QueryMod) killmailQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.KillmailID),
	}

	queryMods = append(queryMods, mods...)

	query := Killmails(queryMods...)
	queries.SetFrom(query.Query, "`killmails`")

	return query
}

// ShipType pointed to by the foreign key.
func (o *KillmailVictim) ShipType(mods ...qm.QueryMod) typeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.ShipTypeID),
	}

	queryMods = append(queryMods, mods...)

	query := Types(queryMods...)
	queries.SetFrom(query.Query, "`types`")

	return query
}

// LoadAlliance allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (killmailVictimL) LoadAlliance(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKillmailVictim interface{}, mods queries.Applicator) error {
	var slice []*KillmailVictim
	var object *KillmailVictim

	if singular {
		object = maybeKillmailVictim.(*KillmailVictim)
	} else {
		slice = *maybeKillmailVictim.(*[]*KillmailVictim)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &killmailVictimR{}
		}
		if !queries.IsNil(object.AllianceID) {
			args = append(args, object.AllianceID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &killmailVictimR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.AllianceID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.AllianceID) {
				args = append(args, obj.AllianceID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`alliances`), qm.WhereIn(`alliances.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Alliance")
	}

	var resultSlice []*Alliance
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Alliance")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for alliances")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for alliances")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Alliance = foreign
		if foreign.R == nil {
			foreign.R = &allianceR{}
		}
		foreign.R.KillmailVictims = append(foreign.R.KillmailVictims, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.AllianceID, foreign.ID) {
				local.R.Alliance = foreign
				if foreign.R == nil {
					foreign.R = &allianceR{}
				}
				foreign.R.KillmailVictims = append(foreign.R.KillmailVictims, local)
				break
			}
		}
	}

	return nil
}

// LoadCharacter allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (killmailVictimL) LoadCharacter(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKillmailVictim interface{}, mods queries.Applicator) error {
	var slice []*KillmailVictim
	var object *KillmailVictim

	if singular {
		object = maybeKillmailVictim.(*KillmailVictim)
	} else {
		slice = *maybeKillmailVictim.(*[]*KillmailVictim)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &killmailVictimR{}
		}
		if !queries.IsNil(object.CharacterID) {
			args = append(args, object.CharacterID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &killmailVictimR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.CharacterID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.CharacterID) {
				args = append(args, obj.CharacterID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`characters`), qm.WhereIn(`characters.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Character")
	}

	var resultSlice []*Character
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Character")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for characters")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for characters")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Character = foreign
		if foreign.R == nil {
			foreign.R = &characterR{}
		}
		foreign.R.KillmailVictims = append(foreign.R.KillmailVictims, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.CharacterID, foreign.ID) {
				local.R.Character = foreign
				if foreign.R == nil {
					foreign.R = &characterR{}
				}
				foreign.R.KillmailVictims = append(foreign.R.KillmailVictims, local)
				break
			}
		}
	}

	return nil
}

// LoadCorporation allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (killmailVictimL) LoadCorporation(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKillmailVictim interface{}, mods queries.Applicator) error {
	var slice []*KillmailVictim
	var object *KillmailVictim

	if singular {
		object = maybeKillmailVictim.(*KillmailVictim)
	} else {
		slice = *maybeKillmailVictim.(*[]*KillmailVictim)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &killmailVictimR{}
		}
		args = append(args, object.CorporationID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &killmailVictimR{}
			}

			for _, a := range args {
				if a == obj.CorporationID {
					continue Outer
				}
			}

			args = append(args, obj.CorporationID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`corporations`), qm.WhereIn(`corporations.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Corporation")
	}

	var resultSlice []*Corporation
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Corporation")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for corporations")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for corporations")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Corporation = foreign
		if foreign.R == nil {
			foreign.R = &corporationR{}
		}
		foreign.R.KillmailVictims = append(foreign.R.KillmailVictims, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CorporationID == foreign.ID {
				local.R.Corporation = foreign
				if foreign.R == nil {
					foreign.R = &corporationR{}
				}
				foreign.R.KillmailVictims = append(foreign.R.KillmailVictims, local)
				break
			}
		}
	}

	return nil
}

// LoadFaction allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (killmailVictimL) LoadFaction(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKillmailVictim interface{}, mods queries.Applicator) error {
	var slice []*KillmailVictim
	var object *KillmailVictim

	if singular {
		object = maybeKillmailVictim.(*KillmailVictim)
	} else {
		slice = *maybeKillmailVictim.(*[]*KillmailVictim)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &killmailVictimR{}
		}
		if !queries.IsNil(object.FactionID) {
			args = append(args, object.FactionID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &killmailVictimR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.FactionID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.FactionID) {
				args = append(args, obj.FactionID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`factions`), qm.WhereIn(`factions.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Faction")
	}

	var resultSlice []*Faction
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Faction")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for factions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for factions")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Faction = foreign
		if foreign.R == nil {
			foreign.R = &factionR{}
		}
		foreign.R.KillmailVictims = append(foreign.R.KillmailVictims, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.FactionID, foreign.ID) {
				local.R.Faction = foreign
				if foreign.R == nil {
					foreign.R = &factionR{}
				}
				foreign.R.KillmailVictims = append(foreign.R.KillmailVictims, local)
				break
			}
		}
	}

	return nil
}

// LoadKillmail allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (killmailVictimL) LoadKillmail(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKillmailVictim interface{}, mods queries.Applicator) error {
	var slice []*KillmailVictim
	var object *KillmailVictim

	if singular {
		object = maybeKillmailVictim.(*KillmailVictim)
	} else {
		slice = *maybeKillmailVictim.(*[]*KillmailVictim)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &killmailVictimR{}
		}
		args = append(args, object.KillmailID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &killmailVictimR{}
			}

			for _, a := range args {
				if a == obj.KillmailID {
					continue Outer
				}
			}

			args = append(args, obj.KillmailID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`killmails`), qm.WhereIn(`killmails.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Killmail")
	}

	var resultSlice []*Killmail
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Killmail")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for killmails")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for killmails")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Killmail = foreign
		if foreign.R == nil {
			foreign.R = &killmailR{}
		}
		foreign.R.KillmailVictims = append(foreign.R.KillmailVictims, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.KillmailID == foreign.ID {
				local.R.Killmail = foreign
				if foreign.R == nil {
					foreign.R = &killmailR{}
				}
				foreign.R.KillmailVictims = append(foreign.R.KillmailVictims, local)
				break
			}
		}
	}

	return nil
}

// LoadShipType allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (killmailVictimL) LoadShipType(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKillmailVictim interface{}, mods queries.Applicator) error {
	var slice []*KillmailVictim
	var object *KillmailVictim

	if singular {
		object = maybeKillmailVictim.(*KillmailVictim)
	} else {
		slice = *maybeKillmailVictim.(*[]*KillmailVictim)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &killmailVictimR{}
		}
		args = append(args, object.ShipTypeID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &killmailVictimR{}
			}

			for _, a := range args {
				if a == obj.ShipTypeID {
					continue Outer
				}
			}

			args = append(args, obj.ShipTypeID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`types`), qm.WhereIn(`types.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Type")
	}

	var resultSlice []*Type
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Type")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for types")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for types")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ShipType = foreign
		if foreign.R == nil {
			foreign.R = &typeR{}
		}
		foreign.R.ShipTypeKillmailVictims = append(foreign.R.ShipTypeKillmailVictims, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ShipTypeID == foreign.ID {
				local.R.ShipType = foreign
				if foreign.R == nil {
					foreign.R = &typeR{}
				}
				foreign.R.ShipTypeKillmailVictims = append(foreign.R.ShipTypeKillmailVictims, local)
				break
			}
		}
	}

	return nil
}

// SetAlliance of the killmailVictim to the related item.
// Sets o.R.Alliance to related.
// Adds o to related.R.KillmailVictims.
func (o *KillmailVictim) SetAlliance(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Alliance) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `killmail_victim` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"alliance_id"}),
		strmangle.WhereClause("`", "`", 0, killmailVictimPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.AllianceID, related.ID)
	if o.R == nil {
		o.R = &killmailVictimR{
			Alliance: related,
		}
	} else {
		o.R.Alliance = related
	}

	if related.R == nil {
		related.R = &allianceR{
			KillmailVictims: KillmailVictimSlice{o},
		}
	} else {
		related.R.KillmailVictims = append(related.R.KillmailVictims, o)
	}

	return nil
}

// RemoveAlliance relationship.
// Sets o.R.Alliance to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *KillmailVictim) RemoveAlliance(ctx context.Context, exec boil.ContextExecutor, related *Alliance) error {
	var err error

	queries.SetScanner(&o.AllianceID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("alliance_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.Alliance = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.KillmailVictims {
		if queries.Equal(o.AllianceID, ri.AllianceID) {
			continue
		}

		ln := len(related.R.KillmailVictims)
		if ln > 1 && i < ln-1 {
			related.R.KillmailVictims[i] = related.R.KillmailVictims[ln-1]
		}
		related.R.KillmailVictims = related.R.KillmailVictims[:ln-1]
		break
	}
	return nil
}

// SetCharacter of the killmailVictim to the related item.
// Sets o.R.Character to related.
// Adds o to related.R.KillmailVictims.
func (o *KillmailVictim) SetCharacter(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Character) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `killmail_victim` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"character_id"}),
		strmangle.WhereClause("`", "`", 0, killmailVictimPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.CharacterID, related.ID)
	if o.R == nil {
		o.R = &killmailVictimR{
			Character: related,
		}
	} else {
		o.R.Character = related
	}

	if related.R == nil {
		related.R = &characterR{
			KillmailVictims: KillmailVictimSlice{o},
		}
	} else {
		related.R.KillmailVictims = append(related.R.KillmailVictims, o)
	}

	return nil
}

// RemoveCharacter relationship.
// Sets o.R.Character to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *KillmailVictim) RemoveCharacter(ctx context.Context, exec boil.ContextExecutor, related *Character) error {
	var err error

	queries.SetScanner(&o.CharacterID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("character_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.Character = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.KillmailVictims {
		if queries.Equal(o.CharacterID, ri.CharacterID) {
			continue
		}

		ln := len(related.R.KillmailVictims)
		if ln > 1 && i < ln-1 {
			related.R.KillmailVictims[i] = related.R.KillmailVictims[ln-1]
		}
		related.R.KillmailVictims = related.R.KillmailVictims[:ln-1]
		break
	}
	return nil
}

// SetCorporation of the killmailVictim to the related item.
// Sets o.R.Corporation to related.
// Adds o to related.R.KillmailVictims.
func (o *KillmailVictim) SetCorporation(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Corporation) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `killmail_victim` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"corporation_id"}),
		strmangle.WhereClause("`", "`", 0, killmailVictimPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CorporationID = related.ID
	if o.R == nil {
		o.R = &killmailVictimR{
			Corporation: related,
		}
	} else {
		o.R.Corporation = related
	}

	if related.R == nil {
		related.R = &corporationR{
			KillmailVictims: KillmailVictimSlice{o},
		}
	} else {
		related.R.KillmailVictims = append(related.R.KillmailVictims, o)
	}

	return nil
}

// SetFaction of the killmailVictim to the related item.
// Sets o.R.Faction to related.
// Adds o to related.R.KillmailVictims.
func (o *KillmailVictim) SetFaction(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Faction) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `killmail_victim` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"faction_id"}),
		strmangle.WhereClause("`", "`", 0, killmailVictimPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.FactionID, related.ID)
	if o.R == nil {
		o.R = &killmailVictimR{
			Faction: related,
		}
	} else {
		o.R.Faction = related
	}

	if related.R == nil {
		related.R = &factionR{
			KillmailVictims: KillmailVictimSlice{o},
		}
	} else {
		related.R.KillmailVictims = append(related.R.KillmailVictims, o)
	}

	return nil
}

// RemoveFaction relationship.
// Sets o.R.Faction to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *KillmailVictim) RemoveFaction(ctx context.Context, exec boil.ContextExecutor, related *Faction) error {
	var err error

	queries.SetScanner(&o.FactionID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("faction_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.Faction = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.KillmailVictims {
		if queries.Equal(o.FactionID, ri.FactionID) {
			continue
		}

		ln := len(related.R.KillmailVictims)
		if ln > 1 && i < ln-1 {
			related.R.KillmailVictims[i] = related.R.KillmailVictims[ln-1]
		}
		related.R.KillmailVictims = related.R.KillmailVictims[:ln-1]
		break
	}
	return nil
}

// SetKillmail of the killmailVictim to the related item.
// Sets o.R.Killmail to related.
// Adds o to related.R.KillmailVictims.
func (o *KillmailVictim) SetKillmail(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Killmail) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `killmail_victim` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"killmail_id"}),
		strmangle.WhereClause("`", "`", 0, killmailVictimPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.KillmailID = related.ID
	if o.R == nil {
		o.R = &killmailVictimR{
			Killmail: related,
		}
	} else {
		o.R.Killmail = related
	}

	if related.R == nil {
		related.R = &killmailR{
			KillmailVictims: KillmailVictimSlice{o},
		}
	} else {
		related.R.KillmailVictims = append(related.R.KillmailVictims, o)
	}

	return nil
}

// SetShipType of the killmailVictim to the related item.
// Sets o.R.ShipType to related.
// Adds o to related.R.ShipTypeKillmailVictims.
func (o *KillmailVictim) SetShipType(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Type) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `killmail_victim` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"ship_type_id"}),
		strmangle.WhereClause("`", "`", 0, killmailVictimPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ShipTypeID = related.ID
	if o.R == nil {
		o.R = &killmailVictimR{
			ShipType: related,
		}
	} else {
		o.R.ShipType = related
	}

	if related.R == nil {
		related.R = &typeR{
			ShipTypeKillmailVictims: KillmailVictimSlice{o},
		}
	} else {
		related.R.ShipTypeKillmailVictims = append(related.R.ShipTypeKillmailVictims, o)
	}

	return nil
}

// KillmailVictims retrieves all the records using an executor.
func KillmailVictims(mods ...qm.QueryMod) killmailVictimQuery {
	mods = append(mods, qm.From("`killmail_victim`"))
	return killmailVictimQuery{NewQuery(mods...)}
}

// FindKillmailVictim retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindKillmailVictim(ctx context.Context, exec boil.ContextExecutor, iD uint64, selectCols ...string) (*KillmailVictim, error) {
	killmailVictimObj := &KillmailVictim{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `killmail_victim` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, killmailVictimObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: unable to select from killmail_victim")
	}

	return killmailVictimObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *KillmailVictim) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no killmail_victim provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(killmailVictimColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	killmailVictimInsertCacheMut.RLock()
	cache, cached := killmailVictimInsertCache[key]
	killmailVictimInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			killmailVictimAllColumns,
			killmailVictimColumnsWithDefault,
			killmailVictimColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(killmailVictimType, killmailVictimMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(killmailVictimType, killmailVictimMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `killmail_victim` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `killmail_victim` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `killmail_victim` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, killmailVictimPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "boiler: unable to insert into killmail_victim")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == killmailVictimMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to populate default values for killmail_victim")
	}

CacheNoHooks:
	if !cached {
		killmailVictimInsertCacheMut.Lock()
		killmailVictimInsertCache[key] = cache
		killmailVictimInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the KillmailVictim.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *KillmailVictim) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	killmailVictimUpdateCacheMut.RLock()
	cache, cached := killmailVictimUpdateCache[key]
	killmailVictimUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			killmailVictimAllColumns,
			killmailVictimPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("boiler: unable to update killmail_victim, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `killmail_victim` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, killmailVictimPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(killmailVictimType, killmailVictimMapping, append(wl, killmailVictimPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update killmail_victim row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by update for killmail_victim")
	}

	if !cached {
		killmailVictimUpdateCacheMut.Lock()
		killmailVictimUpdateCache[key] = cache
		killmailVictimUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q killmailVictimQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all for killmail_victim")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected for killmail_victim")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o KillmailVictimSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("boiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), killmailVictimPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `killmail_victim` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, killmailVictimPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all in killmailVictim slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected all in update all killmailVictim")
	}
	return rowsAff, nil
}

var mySQLKillmailVictimUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *KillmailVictim) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no killmail_victim provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(killmailVictimColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLKillmailVictimUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	killmailVictimUpsertCacheMut.RLock()
	cache, cached := killmailVictimUpsertCache[key]
	killmailVictimUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			killmailVictimAllColumns,
			killmailVictimColumnsWithDefault,
			killmailVictimColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			killmailVictimAllColumns,
			killmailVictimPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("boiler: unable to upsert killmail_victim, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "killmail_victim", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `killmail_victim` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(killmailVictimType, killmailVictimMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(killmailVictimType, killmailVictimMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "boiler: unable to upsert for killmail_victim")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == killmailVictimMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(killmailVictimType, killmailVictimMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to retrieve unique values for killmail_victim")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to populate default values for killmail_victim")
	}

CacheNoHooks:
	if !cached {
		killmailVictimUpsertCacheMut.Lock()
		killmailVictimUpsertCache[key] = cache
		killmailVictimUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single KillmailVictim record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *KillmailVictim) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("boiler: no KillmailVictim provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), killmailVictimPrimaryKeyMapping)
	sql := "DELETE FROM `killmail_victim` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete from killmail_victim")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by delete for killmail_victim")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q killmailVictimQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("boiler: no killmailVictimQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from killmail_victim")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for killmail_victim")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o KillmailVictimSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), killmailVictimPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `killmail_victim` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, killmailVictimPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from killmailVictim slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for killmail_victim")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *KillmailVictim) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindKillmailVictim(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *KillmailVictimSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := KillmailVictimSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), killmailVictimPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `killmail_victim`.* FROM `killmail_victim` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, killmailVictimPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to reload all in KillmailVictimSlice")
	}

	*o = slice

	return nil
}

// KillmailVictimExists checks if the KillmailVictim row exists.
func KillmailVictimExists(ctx context.Context, exec boil.ContextExecutor, iD uint64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `killmail_victim` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "boiler: unable to check if killmail_victim exists")
	}

	return exists, nil
}
