// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// KillmailItem is an object representing the database table.
type KillmailItem struct {
	ID                uint64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ParentID          null.Uint64 `boil:"parent_id" json:"parent_id,omitempty" toml:"parent_id" yaml:"parent_id,omitempty"`
	KillmailID        uint64      `boil:"killmail_id" json:"killmail_id" toml:"killmail_id" yaml:"killmail_id"`
	FlagID            uint64      `boil:"flag_id" json:"flag_id" toml:"flag_id" yaml:"flag_id"`
	ItemTypeID        uint64      `boil:"item_type_id" json:"item_type_id" toml:"item_type_id" yaml:"item_type_id"`
	QuantityDropped   null.Uint64 `boil:"quantity_dropped" json:"quantity_dropped,omitempty" toml:"quantity_dropped" yaml:"quantity_dropped,omitempty"`
	QuantityDestroyed null.Uint64 `boil:"quantity_destroyed" json:"quantity_destroyed,omitempty" toml:"quantity_destroyed" yaml:"quantity_destroyed,omitempty"`
	Singleton         uint64      `boil:"singleton" json:"singleton" toml:"singleton" yaml:"singleton"`
	IsParent          bool        `boil:"is_parent" json:"is_parent" toml:"is_parent" yaml:"is_parent"`
	CreatedAt         time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt         time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *killmailItemR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L killmailItemL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var KillmailItemColumns = struct {
	ID                string
	ParentID          string
	KillmailID        string
	FlagID            string
	ItemTypeID        string
	QuantityDropped   string
	QuantityDestroyed string
	Singleton         string
	IsParent          string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "id",
	ParentID:          "parent_id",
	KillmailID:        "killmail_id",
	FlagID:            "flag_id",
	ItemTypeID:        "item_type_id",
	QuantityDropped:   "quantity_dropped",
	QuantityDestroyed: "quantity_destroyed",
	Singleton:         "singleton",
	IsParent:          "is_parent",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
}

// Generated where

var KillmailItemWhere = struct {
	ID                whereHelperuint64
	ParentID          whereHelpernull_Uint64
	KillmailID        whereHelperuint64
	FlagID            whereHelperuint64
	ItemTypeID        whereHelperuint64
	QuantityDropped   whereHelpernull_Uint64
	QuantityDestroyed whereHelpernull_Uint64
	Singleton         whereHelperuint64
	IsParent          whereHelperbool
	CreatedAt         whereHelpertime_Time
	UpdatedAt         whereHelpertime_Time
}{
	ID:                whereHelperuint64{field: "`killmail_items`.`id`"},
	ParentID:          whereHelpernull_Uint64{field: "`killmail_items`.`parent_id`"},
	KillmailID:        whereHelperuint64{field: "`killmail_items`.`killmail_id`"},
	FlagID:            whereHelperuint64{field: "`killmail_items`.`flag_id`"},
	ItemTypeID:        whereHelperuint64{field: "`killmail_items`.`item_type_id`"},
	QuantityDropped:   whereHelpernull_Uint64{field: "`killmail_items`.`quantity_dropped`"},
	QuantityDestroyed: whereHelpernull_Uint64{field: "`killmail_items`.`quantity_destroyed`"},
	Singleton:         whereHelperuint64{field: "`killmail_items`.`singleton`"},
	IsParent:          whereHelperbool{field: "`killmail_items`.`is_parent`"},
	CreatedAt:         whereHelpertime_Time{field: "`killmail_items`.`created_at`"},
	UpdatedAt:         whereHelpertime_Time{field: "`killmail_items`.`updated_at`"},
}

// KillmailItemRels is where relationship names are stored.
var KillmailItemRels = struct {
	Flag                string
	ItemType            string
	Killmail            string
	Parent              string
	ParentKillmailItems string
}{
	Flag:                "Flag",
	ItemType:            "ItemType",
	Killmail:            "Killmail",
	Parent:              "Parent",
	ParentKillmailItems: "ParentKillmailItems",
}

// killmailItemR is where relationships are stored.
type killmailItemR struct {
	Flag                *TypeFlag
	ItemType            *Type
	Killmail            *Killmail
	Parent              *KillmailItem
	ParentKillmailItems KillmailItemSlice
}

// NewStruct creates a new relationship struct
func (*killmailItemR) NewStruct() *killmailItemR {
	return &killmailItemR{}
}

// killmailItemL is where Load methods for each relationship are stored.
type killmailItemL struct{}

var (
	killmailItemAllColumns            = []string{"id", "parent_id", "killmail_id", "flag_id", "item_type_id", "quantity_dropped", "quantity_destroyed", "singleton", "is_parent", "created_at", "updated_at"}
	killmailItemColumnsWithoutDefault = []string{"parent_id", "killmail_id", "flag_id", "item_type_id", "quantity_dropped", "quantity_destroyed", "singleton", "is_parent", "created_at", "updated_at"}
	killmailItemColumnsWithDefault    = []string{"id"}
	killmailItemPrimaryKeyColumns     = []string{"id"}
)

type (
	// KillmailItemSlice is an alias for a slice of pointers to KillmailItem.
	// This should generally be used opposed to []KillmailItem.
	KillmailItemSlice []*KillmailItem

	killmailItemQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	killmailItemType                 = reflect.TypeOf(&KillmailItem{})
	killmailItemMapping              = queries.MakeStructMapping(killmailItemType)
	killmailItemPrimaryKeyMapping, _ = queries.BindMapping(killmailItemType, killmailItemMapping, killmailItemPrimaryKeyColumns)
	killmailItemInsertCacheMut       sync.RWMutex
	killmailItemInsertCache          = make(map[string]insertCache)
	killmailItemUpdateCacheMut       sync.RWMutex
	killmailItemUpdateCache          = make(map[string]updateCache)
	killmailItemUpsertCacheMut       sync.RWMutex
	killmailItemUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single killmailItem record from the query.
func (q killmailItemQuery) One(ctx context.Context, exec boil.ContextExecutor) (*KillmailItem, error) {
	o := &KillmailItem{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: failed to execute a one query for killmail_items")
	}

	return o, nil
}

// All returns all KillmailItem records from the query.
func (q killmailItemQuery) All(ctx context.Context, exec boil.ContextExecutor) (KillmailItemSlice, error) {
	var o []*KillmailItem

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "boiler: failed to assign all query results to KillmailItem slice")
	}

	return o, nil
}

// Count returns the count of all KillmailItem records in the query.
func (q killmailItemQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to count killmail_items rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q killmailItemQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "boiler: failed to check if killmail_items exists")
	}

	return count > 0, nil
}

// Flag pointed to by the foreign key.
func (o *KillmailItem) Flag(mods ...qm.QueryMod) typeFlagQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.FlagID),
	}

	queryMods = append(queryMods, mods...)

	query := TypeFlags(queryMods...)
	queries.SetFrom(query.Query, "`type_flags`")

	return query
}

// ItemType pointed to by the foreign key.
func (o *KillmailItem) ItemType(mods ...qm.QueryMod) typeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.ItemTypeID),
	}

	queryMods = append(queryMods, mods...)

	query := Types(queryMods...)
	queries.SetFrom(query.Query, "`types`")

	return query
}

// Killmail pointed to by the foreign key.
func (o *KillmailItem) Killmail(mods ...qm.QueryMod) killmailQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.KillmailID),
	}

	queryMods = append(queryMods, mods...)

	query := Killmails(queryMods...)
	queries.SetFrom(query.Query, "`killmails`")

	return query
}

// Parent pointed to by the foreign key.
func (o *KillmailItem) Parent(mods ...qm.QueryMod) killmailItemQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.ParentID),
	}

	queryMods = append(queryMods, mods...)

	query := KillmailItems(queryMods...)
	queries.SetFrom(query.Query, "`killmail_items`")

	return query
}

// ParentKillmailItems retrieves all the killmail_item's KillmailItems with an executor via parent_id column.
func (o *KillmailItem) ParentKillmailItems(mods ...qm.QueryMod) killmailItemQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`killmail_items`.`parent_id`=?", o.ID),
	)

	query := KillmailItems(queryMods...)
	queries.SetFrom(query.Query, "`killmail_items`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`killmail_items`.*"})
	}

	return query
}

// LoadFlag allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (killmailItemL) LoadFlag(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKillmailItem interface{}, mods queries.Applicator) error {
	var slice []*KillmailItem
	var object *KillmailItem

	if singular {
		object = maybeKillmailItem.(*KillmailItem)
	} else {
		slice = *maybeKillmailItem.(*[]*KillmailItem)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &killmailItemR{}
		}
		args = append(args, object.FlagID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &killmailItemR{}
			}

			for _, a := range args {
				if a == obj.FlagID {
					continue Outer
				}
			}

			args = append(args, obj.FlagID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`type_flags`), qm.WhereIn(`type_flags.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TypeFlag")
	}

	var resultSlice []*TypeFlag
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TypeFlag")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for type_flags")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for type_flags")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Flag = foreign
		if foreign.R == nil {
			foreign.R = &typeFlagR{}
		}
		foreign.R.FlagKillmailItems = append(foreign.R.FlagKillmailItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FlagID == foreign.ID {
				local.R.Flag = foreign
				if foreign.R == nil {
					foreign.R = &typeFlagR{}
				}
				foreign.R.FlagKillmailItems = append(foreign.R.FlagKillmailItems, local)
				break
			}
		}
	}

	return nil
}

// LoadItemType allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (killmailItemL) LoadItemType(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKillmailItem interface{}, mods queries.Applicator) error {
	var slice []*KillmailItem
	var object *KillmailItem

	if singular {
		object = maybeKillmailItem.(*KillmailItem)
	} else {
		slice = *maybeKillmailItem.(*[]*KillmailItem)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &killmailItemR{}
		}
		args = append(args, object.ItemTypeID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &killmailItemR{}
			}

			for _, a := range args {
				if a == obj.ItemTypeID {
					continue Outer
				}
			}

			args = append(args, obj.ItemTypeID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`types`), qm.WhereIn(`types.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Type")
	}

	var resultSlice []*Type
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Type")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for types")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for types")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ItemType = foreign
		if foreign.R == nil {
			foreign.R = &typeR{}
		}
		foreign.R.ItemTypeKillmailItems = append(foreign.R.ItemTypeKillmailItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ItemTypeID == foreign.ID {
				local.R.ItemType = foreign
				if foreign.R == nil {
					foreign.R = &typeR{}
				}
				foreign.R.ItemTypeKillmailItems = append(foreign.R.ItemTypeKillmailItems, local)
				break
			}
		}
	}

	return nil
}

// LoadKillmail allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (killmailItemL) LoadKillmail(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKillmailItem interface{}, mods queries.Applicator) error {
	var slice []*KillmailItem
	var object *KillmailItem

	if singular {
		object = maybeKillmailItem.(*KillmailItem)
	} else {
		slice = *maybeKillmailItem.(*[]*KillmailItem)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &killmailItemR{}
		}
		args = append(args, object.KillmailID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &killmailItemR{}
			}

			for _, a := range args {
				if a == obj.KillmailID {
					continue Outer
				}
			}

			args = append(args, obj.KillmailID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`killmails`), qm.WhereIn(`killmails.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Killmail")
	}

	var resultSlice []*Killmail
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Killmail")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for killmails")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for killmails")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Killmail = foreign
		if foreign.R == nil {
			foreign.R = &killmailR{}
		}
		foreign.R.KillmailItems = append(foreign.R.KillmailItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.KillmailID == foreign.ID {
				local.R.Killmail = foreign
				if foreign.R == nil {
					foreign.R = &killmailR{}
				}
				foreign.R.KillmailItems = append(foreign.R.KillmailItems, local)
				break
			}
		}
	}

	return nil
}

// LoadParent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (killmailItemL) LoadParent(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKillmailItem interface{}, mods queries.Applicator) error {
	var slice []*KillmailItem
	var object *KillmailItem

	if singular {
		object = maybeKillmailItem.(*KillmailItem)
	} else {
		slice = *maybeKillmailItem.(*[]*KillmailItem)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &killmailItemR{}
		}
		if !queries.IsNil(object.ParentID) {
			args = append(args, object.ParentID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &killmailItemR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ParentID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.ParentID) {
				args = append(args, obj.ParentID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`killmail_items`), qm.WhereIn(`killmail_items.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load KillmailItem")
	}

	var resultSlice []*KillmailItem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice KillmailItem")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for killmail_items")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for killmail_items")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Parent = foreign
		if foreign.R == nil {
			foreign.R = &killmailItemR{}
		}
		foreign.R.ParentKillmailItems = append(foreign.R.ParentKillmailItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ParentID, foreign.ID) {
				local.R.Parent = foreign
				if foreign.R == nil {
					foreign.R = &killmailItemR{}
				}
				foreign.R.ParentKillmailItems = append(foreign.R.ParentKillmailItems, local)
				break
			}
		}
	}

	return nil
}

// LoadParentKillmailItems allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (killmailItemL) LoadParentKillmailItems(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKillmailItem interface{}, mods queries.Applicator) error {
	var slice []*KillmailItem
	var object *KillmailItem

	if singular {
		object = maybeKillmailItem.(*KillmailItem)
	} else {
		slice = *maybeKillmailItem.(*[]*KillmailItem)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &killmailItemR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &killmailItemR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`killmail_items`), qm.WhereIn(`killmail_items.parent_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load killmail_items")
	}

	var resultSlice []*KillmailItem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice killmail_items")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on killmail_items")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for killmail_items")
	}

	if singular {
		object.R.ParentKillmailItems = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &killmailItemR{}
			}
			foreign.R.Parent = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ParentID) {
				local.R.ParentKillmailItems = append(local.R.ParentKillmailItems, foreign)
				if foreign.R == nil {
					foreign.R = &killmailItemR{}
				}
				foreign.R.Parent = local
				break
			}
		}
	}

	return nil
}

// SetFlag of the killmailItem to the related item.
// Sets o.R.Flag to related.
// Adds o to related.R.FlagKillmailItems.
func (o *KillmailItem) SetFlag(ctx context.Context, exec boil.ContextExecutor, insert bool, related *TypeFlag) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `killmail_items` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"flag_id"}),
		strmangle.WhereClause("`", "`", 0, killmailItemPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FlagID = related.ID
	if o.R == nil {
		o.R = &killmailItemR{
			Flag: related,
		}
	} else {
		o.R.Flag = related
	}

	if related.R == nil {
		related.R = &typeFlagR{
			FlagKillmailItems: KillmailItemSlice{o},
		}
	} else {
		related.R.FlagKillmailItems = append(related.R.FlagKillmailItems, o)
	}

	return nil
}

// SetItemType of the killmailItem to the related item.
// Sets o.R.ItemType to related.
// Adds o to related.R.ItemTypeKillmailItems.
func (o *KillmailItem) SetItemType(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Type) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `killmail_items` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"item_type_id"}),
		strmangle.WhereClause("`", "`", 0, killmailItemPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ItemTypeID = related.ID
	if o.R == nil {
		o.R = &killmailItemR{
			ItemType: related,
		}
	} else {
		o.R.ItemType = related
	}

	if related.R == nil {
		related.R = &typeR{
			ItemTypeKillmailItems: KillmailItemSlice{o},
		}
	} else {
		related.R.ItemTypeKillmailItems = append(related.R.ItemTypeKillmailItems, o)
	}

	return nil
}

// SetKillmail of the killmailItem to the related item.
// Sets o.R.Killmail to related.
// Adds o to related.R.KillmailItems.
func (o *KillmailItem) SetKillmail(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Killmail) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `killmail_items` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"killmail_id"}),
		strmangle.WhereClause("`", "`", 0, killmailItemPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.KillmailID = related.ID
	if o.R == nil {
		o.R = &killmailItemR{
			Killmail: related,
		}
	} else {
		o.R.Killmail = related
	}

	if related.R == nil {
		related.R = &killmailR{
			KillmailItems: KillmailItemSlice{o},
		}
	} else {
		related.R.KillmailItems = append(related.R.KillmailItems, o)
	}

	return nil
}

// SetParent of the killmailItem to the related item.
// Sets o.R.Parent to related.
// Adds o to related.R.ParentKillmailItems.
func (o *KillmailItem) SetParent(ctx context.Context, exec boil.ContextExecutor, insert bool, related *KillmailItem) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `killmail_items` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"parent_id"}),
		strmangle.WhereClause("`", "`", 0, killmailItemPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ParentID, related.ID)
	if o.R == nil {
		o.R = &killmailItemR{
			Parent: related,
		}
	} else {
		o.R.Parent = related
	}

	if related.R == nil {
		related.R = &killmailItemR{
			ParentKillmailItems: KillmailItemSlice{o},
		}
	} else {
		related.R.ParentKillmailItems = append(related.R.ParentKillmailItems, o)
	}

	return nil
}

// RemoveParent relationship.
// Sets o.R.Parent to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *KillmailItem) RemoveParent(ctx context.Context, exec boil.ContextExecutor, related *KillmailItem) error {
	var err error

	queries.SetScanner(&o.ParentID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("parent_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.Parent = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ParentKillmailItems {
		if queries.Equal(o.ParentID, ri.ParentID) {
			continue
		}

		ln := len(related.R.ParentKillmailItems)
		if ln > 1 && i < ln-1 {
			related.R.ParentKillmailItems[i] = related.R.ParentKillmailItems[ln-1]
		}
		related.R.ParentKillmailItems = related.R.ParentKillmailItems[:ln-1]
		break
	}
	return nil
}

// AddParentKillmailItems adds the given related objects to the existing relationships
// of the killmail_item, optionally inserting them as new records.
// Appends related to o.R.ParentKillmailItems.
// Sets related.R.Parent appropriately.
func (o *KillmailItem) AddParentKillmailItems(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*KillmailItem) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ParentID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `killmail_items` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"parent_id"}),
				strmangle.WhereClause("`", "`", 0, killmailItemPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ParentID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &killmailItemR{
			ParentKillmailItems: related,
		}
	} else {
		o.R.ParentKillmailItems = append(o.R.ParentKillmailItems, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &killmailItemR{
				Parent: o,
			}
		} else {
			rel.R.Parent = o
		}
	}
	return nil
}

// SetParentKillmailItems removes all previously related items of the
// killmail_item replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Parent's ParentKillmailItems accordingly.
// Replaces o.R.ParentKillmailItems with related.
// Sets related.R.Parent's ParentKillmailItems accordingly.
func (o *KillmailItem) SetParentKillmailItems(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*KillmailItem) error {
	query := "update `killmail_items` set `parent_id` = null where `parent_id` = ?"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ParentKillmailItems {
			queries.SetScanner(&rel.ParentID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Parent = nil
		}

		o.R.ParentKillmailItems = nil
	}
	return o.AddParentKillmailItems(ctx, exec, insert, related...)
}

// RemoveParentKillmailItems relationships from objects passed in.
// Removes related items from R.ParentKillmailItems (uses pointer comparison, removal does not keep order)
// Sets related.R.Parent.
func (o *KillmailItem) RemoveParentKillmailItems(ctx context.Context, exec boil.ContextExecutor, related ...*KillmailItem) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ParentID, nil)
		if rel.R != nil {
			rel.R.Parent = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("parent_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ParentKillmailItems {
			if rel != ri {
				continue
			}

			ln := len(o.R.ParentKillmailItems)
			if ln > 1 && i < ln-1 {
				o.R.ParentKillmailItems[i] = o.R.ParentKillmailItems[ln-1]
			}
			o.R.ParentKillmailItems = o.R.ParentKillmailItems[:ln-1]
			break
		}
	}

	return nil
}

// KillmailItems retrieves all the records using an executor.
func KillmailItems(mods ...qm.QueryMod) killmailItemQuery {
	mods = append(mods, qm.From("`killmail_items`"))
	return killmailItemQuery{NewQuery(mods...)}
}

// FindKillmailItem retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindKillmailItem(ctx context.Context, exec boil.ContextExecutor, iD uint64, selectCols ...string) (*KillmailItem, error) {
	killmailItemObj := &KillmailItem{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `killmail_items` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, killmailItemObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: unable to select from killmail_items")
	}

	return killmailItemObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *KillmailItem) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no killmail_items provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(killmailItemColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	killmailItemInsertCacheMut.RLock()
	cache, cached := killmailItemInsertCache[key]
	killmailItemInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			killmailItemAllColumns,
			killmailItemColumnsWithDefault,
			killmailItemColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(killmailItemType, killmailItemMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(killmailItemType, killmailItemMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `killmail_items` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `killmail_items` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `killmail_items` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, killmailItemPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "boiler: unable to insert into killmail_items")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == killmailItemMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to populate default values for killmail_items")
	}

CacheNoHooks:
	if !cached {
		killmailItemInsertCacheMut.Lock()
		killmailItemInsertCache[key] = cache
		killmailItemInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the KillmailItem.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *KillmailItem) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	killmailItemUpdateCacheMut.RLock()
	cache, cached := killmailItemUpdateCache[key]
	killmailItemUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			killmailItemAllColumns,
			killmailItemPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("boiler: unable to update killmail_items, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `killmail_items` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, killmailItemPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(killmailItemType, killmailItemMapping, append(wl, killmailItemPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update killmail_items row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by update for killmail_items")
	}

	if !cached {
		killmailItemUpdateCacheMut.Lock()
		killmailItemUpdateCache[key] = cache
		killmailItemUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q killmailItemQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all for killmail_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected for killmail_items")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o KillmailItemSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("boiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), killmailItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `killmail_items` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, killmailItemPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all in killmailItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected all in update all killmailItem")
	}
	return rowsAff, nil
}

var mySQLKillmailItemUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *KillmailItem) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no killmail_items provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(killmailItemColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLKillmailItemUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	killmailItemUpsertCacheMut.RLock()
	cache, cached := killmailItemUpsertCache[key]
	killmailItemUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			killmailItemAllColumns,
			killmailItemColumnsWithDefault,
			killmailItemColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			killmailItemAllColumns,
			killmailItemPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("boiler: unable to upsert killmail_items, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "killmail_items", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `killmail_items` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(killmailItemType, killmailItemMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(killmailItemType, killmailItemMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "boiler: unable to upsert for killmail_items")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == killmailItemMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(killmailItemType, killmailItemMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to retrieve unique values for killmail_items")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to populate default values for killmail_items")
	}

CacheNoHooks:
	if !cached {
		killmailItemUpsertCacheMut.Lock()
		killmailItemUpsertCache[key] = cache
		killmailItemUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single KillmailItem record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *KillmailItem) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("boiler: no KillmailItem provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), killmailItemPrimaryKeyMapping)
	sql := "DELETE FROM `killmail_items` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete from killmail_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by delete for killmail_items")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q killmailItemQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("boiler: no killmailItemQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from killmail_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for killmail_items")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o KillmailItemSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), killmailItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `killmail_items` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, killmailItemPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from killmailItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for killmail_items")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *KillmailItem) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindKillmailItem(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *KillmailItemSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := KillmailItemSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), killmailItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `killmail_items`.* FROM `killmail_items` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, killmailItemPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to reload all in KillmailItemSlice")
	}

	*o = slice

	return nil
}

// KillmailItemExists checks if the KillmailItem row exists.
func KillmailItemExists(ctx context.Context, exec boil.ContextExecutor, iD uint64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `killmail_items` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "boiler: unable to check if killmail_items exists")
	}

	return exists, nil
}
