// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"fmt"
	"io"
	"strconv"
)

type Category string

const (
	CategoryAll  Category = "all"
	CategoryKill Category = "kill"
	CategoryLose Category = "lose"
)

var AllCategory = []Category{
	CategoryAll,
	CategoryKill,
	CategoryLose,
}

func (e Category) IsValid() bool {
	switch e {
	case CategoryAll, CategoryKill, CategoryLose:
		return true
	}
	return false
}

func (e Category) String() string {
	return string(e)
}

func (e *Category) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Category(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Category", str)
	}
	return nil
}

func (e Category) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Entity string

const (
	EntityAll           Entity = "all"
	EntityCharacter     Entity = "character"
	EntityCorporation   Entity = "corporation"
	EntityAlliance      Entity = "alliance"
	EntityShip          Entity = "ship"
	EntityShipGroup     Entity = "shipGroup"
	EntitySystem        Entity = "system"
	EntityConstellation Entity = "constellation"
	EntityRegion        Entity = "region"
)

var AllEntity = []Entity{
	EntityAll,
	EntityCharacter,
	EntityCorporation,
	EntityAlliance,
	EntityShip,
	EntityShipGroup,
	EntitySystem,
	EntityConstellation,
	EntityRegion,
}

func (e Entity) IsValid() bool {
	switch e {
	case EntityAll, EntityCharacter, EntityCorporation, EntityAlliance, EntityShip, EntityShipGroup, EntitySystem, EntityConstellation, EntityRegion:
		return true
	}
	return false
}

func (e Entity) String() string {
	return string(e)
}

func (e *Entity) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Entity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Entity", str)
	}
	return nil
}

func (e Entity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
